[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "kll"
authors = [{name = "Jacob Alexander", email = "haata@kiibohd.com"}]
readme = "README.md"
classifiers = [
    "Topic :: Software Development :: Compilers",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Programming Language :: Python :: 3",
]
requires-python = ">=3.5"
dependencies = [
    "layouts>=0.4.9",
    "gitpython",
    "packaging",
]
dynamic = ["version", "description"]

[project.scripts]
kll = "kll:wrapper"

[project.urls]
Home = "https://github.com/kiibohd/kll"
